### ISSUE TITLE
Error when building with yosys for ECP5 with -retime

### ISSUE THREAD

**Issue by rednaz1337** [enjoy-digital/liteeth#53]
Hi, I'm trying to build this project: https://github.com/NiklasFauth/colorlight-led-cube/ which uses LiteEth.
But when building I get this error:

```
7.37. Executing DFFLEGALIZE pass (convert FFs to types supported by the target).
ERROR: Conflicting init values for signal 1'1 (\eternit.ip_tx_liteethipv4checksum_r_next0 [2] = 1'x != 1'0).
```
I don't think it's a problem in the project, because it also happens when I try to synthize only liteeth_core.v from this liteeth.yml without any other code:

```
# This file is Copyright (c) 2020 Florent Kermarrec <florent@enjoy-digital.fr>
# License: BSD

# PHY ----------------------------------------------------------------------
phy:        LiteEthECP5PHYRGMII
vendor:     lattice
# Core ---------------------------------------------------------------------
clk_freq:   125e6
core:       udp
mac_address: 0xAA040000CFCF
ip_address:  192.168.178.50
port:        6000
```
But this only happens when I synthize it in yosys with `synth_ecp5 -retime`, but not without `-retime`.
Is this a problem in LiteEth or yosys?

I'm very new to FPGAs, therefore I don't know what `-retime` does or if it's important.

**Comment by enjoy-digital** [comment]
Hi @rednaz1337,

this behaviour seems to be related to changes in Yosys/ABC since the same LiteEth generated code is still used (since in the colorlight-led-cube directory). You can remove the `-retime` that is only here to improve the timings. It's difficult to provide more support on this, the issue would need to be minimized first.
